# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ab/pymupdf4llm-C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ab/pymupdf4llm-C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/linuxbrew/.linuxbrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/linuxbrew/.linuxbrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/linuxbrew/.linuxbrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ab/pymupdf4llm-C/CMakeFiles /home/ab/pymupdf4llm-C//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ab/pymupdf4llm-C/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tomd

# Build rule for target.
tomd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tomd
.PHONY : tomd

# fast build rule for target.
tomd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/build
.PHONY : tomd/fast

#=============================================================================
# Target rules for targets named to_md

# Build rule for target.
to_md: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 to_md
.PHONY : to_md

# fast build rule for target.
to_md/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/build
.PHONY : to_md/fast

#=============================================================================
# Target rules for targets named test_table_detection

# Build rule for target.
test_table_detection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_table_detection
.PHONY : test_table_detection

# fast build rule for target.
test_table_detection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_table_detection.dir/build.make CMakeFiles/test_table_detection.dir/build
.PHONY : test_table_detection/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test-

# Build rule for target.
test-: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-
.PHONY : test-

# fast build rule for target.
test-/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-.dir/build.make CMakeFiles/test-.dir/build
.PHONY : test-/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

src/get_raw_lines.o: src/get_raw_lines.c.o
.PHONY : src/get_raw_lines.o

# target to build an object file
src/get_raw_lines.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/get_raw_lines.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/get_raw_lines.c.o
.PHONY : src/get_raw_lines.c.o

src/get_raw_lines.i: src/get_raw_lines.c.i
.PHONY : src/get_raw_lines.i

# target to preprocess a source file
src/get_raw_lines.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/get_raw_lines.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/get_raw_lines.c.i
.PHONY : src/get_raw_lines.c.i

src/get_raw_lines.s: src/get_raw_lines.c.s
.PHONY : src/get_raw_lines.s

# target to generate assembly for a file
src/get_raw_lines.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/get_raw_lines.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/get_raw_lines.c.s
.PHONY : src/get_raw_lines.c.s

src/multicolumn.o: src/multicolumn.c.o
.PHONY : src/multicolumn.o

# target to build an object file
src/multicolumn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/multicolumn.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/multicolumn.c.o
.PHONY : src/multicolumn.c.o

src/multicolumn.i: src/multicolumn.c.i
.PHONY : src/multicolumn.i

# target to preprocess a source file
src/multicolumn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/multicolumn.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/multicolumn.c.i
.PHONY : src/multicolumn.c.i

src/multicolumn.s: src/multicolumn.c.s
.PHONY : src/multicolumn.s

# target to generate assembly for a file
src/multicolumn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/multicolumn.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/multicolumn.c.s
.PHONY : src/multicolumn.c.s

src/table.o: src/table.c.o
.PHONY : src/table.o

# target to build an object file
src/table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/table.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/table.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_table_detection.dir/build.make CMakeFiles/test_table_detection.dir/src/table.c.o
.PHONY : src/table.c.o

src/table.i: src/table.c.i
.PHONY : src/table.i

# target to preprocess a source file
src/table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/table.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/table.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_table_detection.dir/build.make CMakeFiles/test_table_detection.dir/src/table.c.i
.PHONY : src/table.c.i

src/table.s: src/table.c.s
.PHONY : src/table.s

# target to generate assembly for a file
src/table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/table.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/table.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_table_detection.dir/build.make CMakeFiles/test_table_detection.dir/src/table.c.s
.PHONY : src/table.c.s

src/to_md.o: src/to_md.c.o
.PHONY : src/to_md.o

# target to build an object file
src/to_md.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/to_md.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/to_md.c.o
.PHONY : src/to_md.c.o

src/to_md.i: src/to_md.c.i
.PHONY : src/to_md.i

# target to preprocess a source file
src/to_md.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/to_md.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/to_md.c.i
.PHONY : src/to_md.c.i

src/to_md.s: src/to_md.c.s
.PHONY : src/to_md.s

# target to generate assembly for a file
src/to_md.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tomd.dir/build.make CMakeFiles/tomd.dir/src/to_md.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/to_md.dir/build.make CMakeFiles/to_md.dir/src/to_md.c.s
.PHONY : src/to_md.c.s

test_table_detection.o: test_table_detection.c.o
.PHONY : test_table_detection.o

# target to build an object file
test_table_detection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_table_detection.dir/build.make CMakeFiles/test_table_detection.dir/test_table_detection.c.o
.PHONY : test_table_detection.c.o

test_table_detection.i: test_table_detection.c.i
.PHONY : test_table_detection.i

# target to preprocess a source file
test_table_detection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_table_detection.dir/build.make CMakeFiles/test_table_detection.dir/test_table_detection.c.i
.PHONY : test_table_detection.c.i

test_table_detection.s: test_table_detection.c.s
.PHONY : test_table_detection.s

# target to generate assembly for a file
test_table_detection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_table_detection.dir/build.make CMakeFiles/test_table_detection.dir/test_table_detection.c.s
.PHONY : test_table_detection.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... benchmark"
	@echo "... test"
	@echo "... test-"
	@echo "... test_table_detection"
	@echo "... to_md"
	@echo "... tomd"
	@echo "... src/get_raw_lines.o"
	@echo "... src/get_raw_lines.i"
	@echo "... src/get_raw_lines.s"
	@echo "... src/multicolumn.o"
	@echo "... src/multicolumn.i"
	@echo "... src/multicolumn.s"
	@echo "... src/table.o"
	@echo "... src/table.i"
	@echo "... src/table.s"
	@echo "... src/to_md.o"
	@echo "... src/to_md.i"
	@echo "... src/to_md.s"
	@echo "... test_table_detection.o"
	@echo "... test_table_detection.i"
	@echo "... test_table_detection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

