# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from binascii import b2a_base64
from collections import defaultdict
from dataclasses import dataclass
from pymupdf import mupdf
from pymupdf4llm.helpers.get_text_lines import get_raw_lines, is_white
from pymupdf4llm.helpers.multi_column import column_boxes
from pymupdf4llm.helpers.progress import ProgressBar
from typing import Any
from typing_extensions import Self
import os
import pymupdf

GRAPHICS_TEXT = '\n![](%s)\n'
class IdentifyHeaders:
    def __init__(self: Self, doc: str, pages: list, body_limit: float, max_levels: int) -> None: ...
    def get_header_id(self: Self, span: dict, page: Any) -> str: ...

class TocHeaders:
    def __init__(self: Self, doc: str) -> None: ...
    def get_header_id(self: Self, span: dict, page: Any) -> str: ...

class Parameters:
def refine_boxes(boxes: Any, enlarge: Any) -> Any:
    ...

def is_significant(box: Any, paths: Any) -> Any:
    ...

def to_markdown(doc: Any) -> str:
    ...

def extract_images_on_page_simple(page: Any, parms: Any, image_size_limit: Any) -> Any:
    ...

def filter_small_images(page: Any, parms: Any, image_size_limit: Any) -> Any:
    ...

def extract_images_on_page_simple_drop(page: Any, parms: Any, image_size_limit: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import binascii
import collections
import collections.defaultdict
import dataclasses
import pymupdf
import pymupdf.mupdf
import pymupdf4llm
import pymupdf4llm.helpers
import pymupdf4llm.helpers.get_text_lines
import pymupdf4llm.helpers.multi_column
import pymupdf4llm.helpers.progress
import posixpath
import pathlib
import sys
import time